baseURL = "https://mpccarbide.com"
title = "Micro-Precision Carbide "
languageCode = "zh"
DefaultContentLanguage = "zh"
enableInlineShortcodes = true
theme = "tella"
enableRobotsTXT = true


[params]

  showBlog = true
  mainSections = ['product']
  blogTitle = "Main Products"
  companyName = "Micro-Precision Carbide"
  googleFonts = true

  [params.logo]
    main = "img/logo/favicon.png"
    alt = "WC Logo"
    size = "h-14"

  [params.site]
  

  [params.icon]
    fontawesome = true

  [params.homepage_meta_tags]

  [params.contact]
    email = "info@mpccarbide.com"
    phone = "+86-18681336970"
   

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "products"
    name = "Products"
    url = "/product/"
    weight = 2

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 4

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
    weight = 3
  [[menu.footer]]
    name = "Email: info@mpccarbide.com"
    url = "/contact/"
    weight=1 

  [[menu.footer]]
    name = "Phone: +86-18681336970"  
    url = "/contact/"
    weight=2
 