baseURL = "https://mpccarbide.com"
title = "Micro-Precision Carbide "
DefaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
enableInlineShortcodes = true
theme = "tella"
enableRobotsTXT = true



[params]
  showBlog = true
  mainSections = ['product']
  googleFonts = true

  [params.logo]
    main = "img/logo/favicon.png"
    alt = "WC Logo"
    size = "h-14"

  [params.icon]
    fontawesome = true

  [params.contact]
    email = "info@mpccarbide.com"
    phone = "+86-18681336970"

# ============= 英文语言配置 =============
[languages.en]
  languageName = "English"
  weight = 1
  contentDir = "content/en"

  [languages.en.params]
    blogTitle = "Main Products"
    companyName = "Micro-Precision Carbide"

  # 英文主菜单
  [[languages.en.menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[languages.en.menu.main]]
    identifier = "products"
    name = "Products"
    url = "/product/"
    weight = 2
  [[languages.en.menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3
  [[languages.en.menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 4

  # 英文页脚菜单
  [[languages.en.menu.footer]]
    name = "Home"
    url = "/"
    weight = 3
  [[languages.en.menu.footer]]
    name = "Email: info@mpccarbide.com"
    url = "/contact/"
    weight = 1
  [[languages.en.menu.footer]]
    name = "Phone: +86-18681336970"
    url = "/contact/"
    weight = 2

# ============= 德文语言配置 =============
[languages.de]
  languageName = "Deutsch"
  weight = 2
  contentDir = "content/de"

  [languages.de.params]
    blogTitle = "Hauptprodukte"
    companyName = "Micro-Precision Carbide"

  # 德文主菜单
  [[languages.de.menu.main]]
    identifier = "home"
    name = "Startseite"
    url = "/de/"           
    weight = 1
  [[languages.de.menu.main]]
    identifier = "products"
    name = "Produkte"
    url = "/de/product/"   
    weight = 2
  [[languages.de.menu.main]]
    identifier = "about"
    name = "Über uns"
    url = "/de/about/"     
    weight = 3
  [[languages.de.menu.main]]
    identifier = "contact"
    name = "Kontakt"
    url = "/de/contact/"   
    weight = 4

  # 德文页脚菜单
  [[languages.de.menu.footer]]
    name = "Startseite"
    url = "/de/"           
    weight = 3
  [[languages.de.menu.footer]]
    name = "E-Mail: info@mpccarbide.com"
    url = "/de/contact/"   
    weight = 1
  [[languages.de.menu.footer]]
    name = "Telefon: +86-18681336970"  
    url = "/de/contact/"   
    weight = 2